server:
  port: 8111
spring:
  application:  
      name: zuulserver
  security:
    user:
      name: admin
      password: password
   






     
zuul:
  routes:
    product:
      path: /api/product
      url: http://localhost:59711/ 
      service-id: product
      
      
